// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewCategoria struct {
	Nome      string  `json:"nome"`
	Descricao *string `json:"descricao,omitempty"`
}

type NewCurso struct {
	Nome        string  `json:"nome"`
	Descricao   *string `json:"descricao,omitempty"`
	CategoriaID string  `json:"categoriaId"`
}

type Query struct {
}
